# Gradle Properties
	org.gradle.jvmargs=-Xmx6G

# Fabric Basic Properties
	# https://fabricmc.net/versions.html
	loader_version=0.19.5

# Mod Properties
	mod_id=core-lib-api
	mod_name=Core Lib API
	mod_version=0.3.0
	maven_group=com.sakuraryoko
	archives_base_name=core-lib-api

# Global Dependencies
	# https://github.com/Fallen-Breath/conditional-mixin
	conditionalmixin_version=0.6.4

	# https://github.com/LlamaLad7/MixinExtras
	mixinextras_version=0.3.6

# External Dependencies
	gson_version = 2.14.0
	opencsv_version = 5.12.0
